apiVersion: v1
kind: Namespace
metadata:
  name: managed-release
  labels:
    konflux-ci.dev/type: tenant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-pipeline
secrets:
- name: mytestworkload-local-konflux-ci-instance-pull-secret
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: simple-python-app
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
  - simple-python-app
  data:
    mapping:
      components:
      - name: simple-python-app
        repositories:
        - url: quay.io/mytestworkload/default-tenant/releases/simple-python-app
        tags:
        - latest
        - "{{ git_sha }}"
        - "{{ git_short_sha }}"
        - "{{ digest_sha }}"
  origin: default-tenant
  pipeline:
    pipelineRef:
      resolver: git
      ociStorage: registry-service.kind-registry/simple-python-app-release-ta
      params:
      - name: url
        value: "https://gitcode.com/qicx/release-service-catalog.git"
      - name: revision
        value: development
      - name: pathInRepo
        value: "pipelines/managed/push-to-external-registry/push-to-external-registry.yaml"
    serviceAccountName: release-pipeline
  policy: default
---
# Make it be able to read ReleasePlanAdmission
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-pipeline-resource-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: release-pipeline
    namespace: managed-release
